Quora/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'question/index'

  resources :questions

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Quora/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Quora/app/models/question.rb
class Question < ApplicationRecord
  validates :title, presence: true,
                    length: { minimum: 5 }
end

Quora/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Quora/app/controllers/question_controller.rb
class QuestionController < ApplicationController
  def index
  end
  def show
    @question = Question.find(params[:id])
  end
  def new
    @question = Question.new
  end
  def create
    @question = Question.new(question_params)
  
    if @question.save
      redirect_to @question 
    else
      render 'new'
    end
  end
 
private
  def question_params
    params.require(:question).permit(:title, :text)
  end
end

Quora/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

Quora/app/helpers/application_helper.rb
module ApplicationHelper
end

Quora/app/helpers/question_helper.rb
module QuestionHelper
end

Quora/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Quora/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quora</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Quora/app/views/question/index.html.erb
<h1>New Question</h1>
<%= form_for :question, url: questions_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

Quora/app/views/welcome/index.html.erb
<h1>Welcome to Quora</h1>
<%  %>